server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/user-registration
    password: kalpitpatel
  application:
    name: Spring-security-tutorial
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'